const keys = [
  {
    key: 'Backquote',
    ru: {
      lowercase: 'ё',
      uppercase: 'Ё',
      capsLowercase: 'Ё',
      capsUppercase: 'ё',
    },
    en: {
      lowercase: '`',
      uppercase: '~',
      capsLowercase: '`',
      capsUppercase: '~',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Digit1',
    ru: {
      lowercase: '1',
      uppercase: '!',
      capsLowercase: '1',
      capsUppercase: '!',
    },
    en: {
      lowercase: '1',
      uppercase: '!',
      capsLowercase: '1',
      capsUppercase: '!',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Digit2',
    ru: {
      lowercase: '2',
      uppercase: '"',
      capsLowercase: '2',
      capsUppercase: '"',
    },
    en: {
      lowercase: '2',
      uppercase: '@',
      capsLowercase: '2',
      capsUppercase: '@',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Digit3',
    ru: {
      lowercase: '3',
      uppercase: '№',
      capsLowercase: '3',
      capsUppercase: '№',
    },
    en: {
      lowercase: '3',
      uppercase: '#',
      capsLowercase: '3',
      capsUppercase: '#',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Digit4',
    ru: {
      lowercase: '4',
      uppercase: ';',
      capsLowercase: '4',
      capsUppercase: ';',
    },
    en: {
      lowercase: '4',
      uppercase: '$',
      capsLowercase: '4',
      capsUppercase: '$',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Digit5',
    ru: {
      lowercase: '5',
      uppercase: '%',
      capsLowercase: '5',
      capsUppercase: '%',
    },
    en: {
      lowercase: '5',
      uppercase: '%',
      capsLowercase: '5',
      capsUppercase: '%',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Digit6',
    ru: {
      lowercase: '6',
      uppercase: ':',
      capsLowercase: '6',
      capsUppercase: ':',
    },
    en: {
      lowercase: '6',
      uppercase: '^',
      capsLowercase: '6',
      capsUppercase: '^',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Digit7',
    ru: {
      lowercase: '7',
      uppercase: '?',
      capsLowercase: '7',
      capsUppercase: '?',
    },
    en: {
      lowercase: '7',
      uppercase: '&',
      capsLowercase: '7',
      capsUppercase: '&',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Digit8',
    ru: {
      lowercase: '8',
      uppercase: '*',
      capsLowercase: '8',
      capsUppercase: '*',
    },
    en: {
      lowercase: '8',
      uppercase: '*',
      capsLowercase: '8',
      capsUppercase: '*',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Digit9',
    ru: {
      lowercase: '9',
      uppercase: '(',
      capsLowercase: '9',
      capsUppercase: '(',
    },
    en: {
      lowercase: '9',
      uppercase: '(',
      capsLowercase: '9',
      capsUppercase: '(',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Digit0',
    ru: {
      lowercase: '0',
      uppercase: ')',
      capsLowercase: '0',
      capsUppercase: ')',
    },
    en: {
      lowercase: '0',
      uppercase: ')',
      capsLowercase: '0',
      capsUppercase: ')',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Minus',
    ru: {
      lowercase: '-',
      uppercase: '_',
      capsLowercase: '-',
      capsUppercase: '_',
    },
    en: {
      lowercase: '-',
      uppercase: '_',
      capsLowercase: '-',
      capsUppercase: '_',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Equal',
    ru: {
      lowercase: '=',
      uppercase: '+',
      capsLowercase: '=',
      capsUppercase: '+',
    },
    en: {
      lowercase: '=',
      uppercase: '+',
      capsLowercase: '=',
      capsUppercase: '+',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Backspace',
    ru: {
      lowercase: 'backspace',
      uppercase: 'backspace',
      capsLowercase: 'backspace',
      capsUppercase: 'backspace',
    },
    en: {
      lowercase: 'backspace',
      uppercase: 'backspace',
      capsLowercase: 'backspace',
      capsUppercase: 'backspace',
    },
    special: true,
    double: true,
  },
  {
    key: 'Tab',
    ru: {
      lowercase: 'tab',
      uppercase: 'tab',
      capsLowercase: 'tab',
      capsUppercase: 'tab',
    },
    en: {
      lowercase: 'tab',
      uppercase: 'tab',
      capsLowercase: 'tab',
      capsUppercase: 'tab',
    },
    special: true,
    double: true,
  },
  {
    key: 'KeyQ',
    ru: {
      lowercase: 'й',
      uppercase: 'Й',
      capsLowercase: 'Й',
      capsUppercase: 'й',
    },
    en: {
      lowercase: 'q',
      uppercase: 'Q',
      capsLowercase: 'Q',
      capsUppercase: 'q',
    },
    double: false,
  },
  {
    key: 'KeyW',
    ru: {
      lowercase: 'ц',
      uppercase: 'Ц',
      capsLowercase: 'Ц',
      capsUppercase: 'ц',
    },
    en: {
      lowercase: 'w',
      uppercase: 'W',
      capsLowercase: 'W',
      capsUppercase: 'w',
    },
    double: false,
  },
  {
    key: 'KeyE',
    ru: {
      lowercase: 'у',
      uppercase: 'У',
      capsLowercase: 'У',
      capsUppercase: 'у',
    },
    en: {
      lowercase: 'e',
      uppercase: 'E',
      capsLowercase: 'E',
      capsUppercase: 'e',
    },
    double: false,
  },
  {
    key: 'KeyR',
    ru: {
      lowercase: 'к',
      uppercase: 'К',
      capsLowercase: 'К',
      capsUppercase: 'к',
    },
    en: {
      lowercase: 'r',
      uppercase: 'R',
      capsLowercase: 'R',
      capsUppercase: 'r',
    },
    double: false,
  },
  {
    key: 'KeyT',
    ru: {
      lowercase: 'е',
      uppercase: 'Е',
      capsLowercase: 'Е',
      capsUppercase: 'е',
    },
    en: {
      lowercase: 't',
      uppercase: 'T',
      capsLowercase: 'T',
      capsUppercase: 't',
    },
    double: false,
  },
  {
    key: 'KeyY',
    ru: {
      lowercase: 'н',
      uppercase: 'Н',
      capsLowercase: 'Н',
      capsUppercase: 'н',
    },
    en: {
      lowercase: 'y',
      uppercase: 'Y',
      capsLowercase: 'Y',
      capsUppercase: 'y',
    },
    double: false,
  },
  {
    key: 'KeyU',
    ru: {
      lowercase: 'г',
      uppercase: 'Г',
      capsLowercase: 'Г',
      capsUppercase: 'г',
    },
    en: {
      lowercase: 'u',
      uppercase: 'U',
      capsLowercase: 'U',
      capsUppercase: 'u',
    },
    double: false,
  },
  {
    key: 'KeyI',
    ru: {
      lowercase: 'ш',
      uppercase: 'Ш',
      capsLowercase: 'Ш',
      capsUppercase: 'ш',
    },
    en: {
      lowercase: 'i',
      uppercase: 'I',
      capsLowercase: 'I',
      capsUppercase: 'i',
    },
    double: false,
  },
  {
    key: 'KeyO',
    ru: {
      lowercase: 'щ',
      uppercase: 'Щ',
      capsLowercase: 'Щ',
      capsUppercase: 'щ',
    },
    en: {
      lowercase: 'o',
      uppercase: 'O',
      capsLowercase: 'O',
      capsUppercase: 'o',
    },
    double: false,
  },
  {
    key: 'KeyP',
    ru: {
      lowercase: 'з',
      uppercase: 'З',
      capsLowercase: 'З',
      capsUppercase: 'з',
    },
    en: {
      lowercase: 'p',
      uppercase: 'P',
      capsLowercase: 'P',
      capsUppercase: 'p',
    },
    double: false,
  },
  {
    key: 'BracketLeft',
    ru: {
      lowercase: 'х',
      uppercase: 'Х',
      capsLowercase: 'Х',
      capsUppercase: 'х',
    },
    en: {
      lowercase: '[',
      uppercase: '{',
      capsLowercase: '[',
      capsUppercase: '{',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'BracketRight',
    ru: {
      lowercase: 'ъ',
      uppercase: 'Ъ',
      capsLowercase: 'Ъ',
      capsUppercase: 'ъ',
    },
    en: {
      lowercase: ']',
      uppercase: '}',
      capsLowercase: ']',
      capsUppercase: '}',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Backslash',
    ru: {
      lowercase: '\\',
      uppercase: '|',
      capsLowercase: '\\',
      capsUppercase: '|',
    },
    en: {
      lowercase: '\\',
      uppercase: '|',
      capsLowercase: '\\',
      capsUppercase: '|',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'CapsLock',
    ru: {
      lowercase: 'capslock',
      uppercase: 'capslock',
      capsLowercase: 'capslock',
      capsUppercase: 'capslock',
    },
    en: {
      lowercase: 'capslock',
      uppercase: 'capslock',
      capsLowercase: 'capslock',
      capsUppercase: 'capslock',
    },
    special: true,
    double: true,
  },
  {
    key: 'KeyA',
    ru: {
      lowercase: 'ф',
      uppercase: 'Ф',
      capsLowercase: 'Ф',
      capsUppercase: 'ф',
    },
    en: {
      lowercase: 'a',
      uppercase: 'A',
      capsLowercase: 'A',
      capsUppercase: 'a',
    },
    double: false,
  },
  {
    key: 'KeyS',
    ru: {
      lowercase: 'ы',
      uppercase: 'Ы',
      capsLowercase: 'Ы',
      capsUppercase: 'ы',
    },
    en: {
      lowercase: 's',
      uppercase: 'S',
      capsLowercase: 'S',
      capsUppercase: 's',
    },
    double: false,
  },
  {
    key: 'KeyD',
    ru: {
      lowercase: 'в',
      uppercase: 'В',
      capsLowercase: 'В',
      capsUppercase: 'в',
    },
    en: {
      lowercase: 'd',
      uppercase: 'D',
      capsLowercase: 'D',
      capsUppercase: 'd',
    },
    double: false,
  },
  {
    key: 'KeyF',
    ru: {
      lowercase: 'а',
      uppercase: 'А',
      capsLowercase: 'А',
      capsUppercase: 'а',
    },
    en: {
      lowercase: 'f',
      uppercase: 'F',
      capsLowercase: 'F',
      capsUppercase: 'f',
    },
    double: false,
  },
  {
    key: 'KeyG',
    ru: {
      lowercase: 'п',
      uppercase: 'П',
      capsLowercase: 'П',
      capsUppercase: 'п',
    },
    en: {
      lowercase: 'g',
      uppercase: 'G',
      capsLowercase: 'G',
      capsUppercase: 'g',
    },
    double: false,
  },
  {
    key: 'KeyH',
    ru: {
      lowercase: 'р',
      uppercase: 'Р',
      capsLowercase: 'Р',
      capsUppercase: 'р',
    },
    en: {
      lowercase: 'h',
      uppercase: 'H',
      capsLowercase: 'H',
      capsUppercase: 'h',
    },
    double: false,
  },
  {
    key: 'KeyJ',
    ru: {
      lowercase: 'о',
      uppercase: 'О',
      capsLowercase: 'О',
      capsUppercase: 'о',
    },
    en: {
      lowercase: 'j',
      uppercase: 'J',
      capsLowercase: 'J',
      capsUppercase: 'j',
    },
    double: false,
  },
  {
    key: 'KeyK',
    ru: {
      lowercase: 'л',
      uppercase: 'Л',
      capsLowercase: 'Л',
      capsUppercase: 'л',
    },
    en: {
      lowercase: 'k',
      uppercase: 'K',
      capsLowercase: 'K',
      capsUppercase: 'k',
    },
    double: false,
  },
  {
    key: 'KeyL',
    ru: {
      lowercase: 'д',
      uppercase: 'Д',
      capsLowercase: 'Д',
      capsUppercase: 'д',
    },
    en: {
      lowercase: 'l',
      uppercase: 'L',
      capsLowercase: 'L',
      capsUppercase: 'l',
    },
    double: false,
  },
  {
    key: 'Semicolon',
    ru: {
      lowercase: 'ж',
      uppercase: 'Ж',
      capsLowercase: 'Ж',
      capsUppercase: 'ж',
    },
    en: {
      lowercase: ';',
      uppercase: ':',
      capsLowercase: ';',
      capsUppercase: ':',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Quote',
    ru: {
      lowercase: 'э',
      uppercase: 'Э',
      capsLowercase: 'Э',
      capsUppercase: 'э',
    },
    en: {
      lowercase: "'",
      uppercase: '"',
      capsLowercase: "'",
      capsUppercase: '"',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Enter',
    ru: {
      lowercase: 'enter',
      uppercase: 'enter',
      capsLowercase: 'enter',
      capsUppercase: 'enter',
    },
    en: {
      lowercase: 'enter',
      uppercase: 'enter',
      capsLowercase: 'enter',
      capsUppercase: 'enter',
    },
    special: true,
    double: true,
  },

  {
    key: 'ShiftLeft',
    ru: {
      lowercase: 'shift',
      uppercase: 'shift',
      capsLowercase: 'shift',
      capsUppercase: 'shift',
    },
    en: {
      lowercase: 'shift',
      uppercase: 'shift',
      capsLowercase: 'shift',
      capsUppercase: 'shift',
    },
    special: true,
    double: true,
  },
  {
    key: 'KeyZ',
    ru: {
      lowercase: 'я',
      uppercase: 'Я',
      capsLowercase: 'Я',
      capsUppercase: 'я',
    },
    en: {
      lowercase: 'z',
      uppercase: 'Z',
      capsLowercase: 'Z',
      capsUppercase: 'z',
    },
    double: false,
  },
  {
    key: 'KeyX',
    ru: {
      lowercase: 'ч',
      uppercase: 'Ч',
      capsLowercase: 'Ч',
      capsUppercase: 'ч',
    },
    en: {
      lowercase: 'x',
      uppercase: 'X',
      capsLowercase: 'X',
      capsUppercase: 'x',
    },
    double: false,
  },
  {
    key: 'KeyC',
    ru: {
      lowercase: 'с',
      uppercase: 'С',
      capsLowercase: 'С',
      capsUppercase: 'с',
    },
    en: {
      lowercase: 'c',
      uppercase: 'C',
      capsLowercase: 'C',
      capsUppercase: 'c',
    },
    double: false,
  },
  {
    key: 'KeyV',
    ru: {
      lowercase: 'м',
      uppercase: 'М',
      capsLowercase: 'М',
      capsUppercase: 'м',
    },
    en: {
      lowercase: 'v',
      uppercase: 'V',
      capsLowercase: 'V',
      capsUppercase: 'v',
    },
    double: false,
  },
  {
    key: 'KeyB',
    ru: {
      lowercase: 'и',
      uppercase: 'И',
      capsLowercase: 'И',
      capsUppercase: 'и',
    },
    en: {
      lowercase: 'b',
      uppercase: 'B',
      capsLowercase: 'B',
      capsUppercase: 'b',
    },
    double: false,
  },
  {
    key: 'KeyN',
    ru: {
      lowercase: 'т',
      uppercase: 'Т',
      capsLowercase: 'Т',
      capsUppercase: 'т',
    },
    en: {
      lowercase: 'n',
      uppercase: 'N',
      capsLowercase: 'N',
      capsUppercase: 'n',
    },
    double: false,
  },
  {
    key: 'KeyM',
    ru: {
      lowercase: 'ь',
      uppercase: 'Ь',
      capsLowercase: 'Ь',
      capsUppercase: 'ь',
    },
    en: {
      lowercase: 'm',
      uppercase: 'M',
      capsLowercase: 'M',
      capsUppercase: 'm',
    },
    double: false,
  },
  {
    key: 'Comma',
    ru: {
      lowercase: 'б',
      uppercase: 'Б',
      capsLowercase: 'Б',
      capsUppercase: 'б',
    },
    en: {
      lowercase: ',',
      uppercase: '<',
      capsLowercase: ',',
      capsUppercase: '<',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Period',
    ru: {
      lowercase: 'ю',
      uppercase: 'Ю',
      capsLowercase: 'Ю',
      capsUppercase: 'ю',
    },
    en: {
      lowercase: '.',
      uppercase: '>',
      capsLowercase: '.',
      capsUppercase: '>',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'Slash',
    ru: {
      lowercase: '.',
      uppercase: ',',
      capsLowercase: '.',
      capsUppercase: ',',
    },
    en: {
      lowercase: '/',
      uppercase: '?',
      capsLowercase: '/',
      capsUppercase: '?',
    },
    shifted: true,
    double: false,
  },
  {
    key: 'ArrowLeft',
    ru: {
      uppercase: '←',
      lowercase: '←',
      capsLowercase: '←',
      capsUppercase: '←',
    },
    en: {
      lowercase: '←',
      uppercase: '←',
      capsLowercase: '←',
      capsUppercase: '←',
    },
    double: false,
  },
  {
    key: 'ArrowUp',
    ru: {
      lowercase: '↑',
      uppercase: '↑',
      capsLowercase: '↑',
      capsUppercase: '↑',
    },
    en: {
      lowercase: '↑',
      uppercase: '↑',
      capsLowercase: '↑',
      capsUppercase: '↑',
    },
    double: false,
  },
  {
    key: 'ShiftRight',
    ru: {
      lowercase: 'shift',
      uppercase: 'shift',
      capsLowercase: 'shift',
      capsUppercase: 'shift',
    },
    en: {
      lowercase: 'shift',
      uppercase: 'shift',
      capsLowercase: 'shift',
      capsUppercase: 'shift',
    },
    special: true,
    double: false,
  },
  {
    key: 'ControlLeft',
    ru: {
      lowercase: 'ctrl',
      uppercase: 'ctrl',
      capsLowercase: 'ctrl',
      capsUppercase: 'ctrl',
    },
    en: {
      lowercase: 'ctrl',
      uppercase: 'ctrl',
      capsLowercase: 'ctrl',
      capsUppercase: 'ctrl',
    },
    special: true,
    double: false,
  },
  {
    key: 'AltLeft',
    ru: {
      lowercase: 'alt',
      uppercase: 'alt',
      capsLowercase: 'alt',
      capsUppercase: 'alt',
    },
    en: {
      lowercase: 'alt',
      uppercase: 'alt',
      capsLowercase: 'alt',
      capsUppercase: 'alt',
    },
    special: true,
    double: false,
  },
  {
    key: 'Space',
    ru: {
      lowercase: 'space',
      uppercase: 'space',
      capsLowercase: 'space',
      capsUppercase: 'space',
    },
    en: {
      lowercase: 'space',
      uppercase: 'space',
      capsLowercase: 'space',
      capsUppercase: 'space',
    },
    special: true,
    double: true,
  },
  {
    key: 'AltRight',
    ru: {
      lowercase: 'alt',
      uppercase: 'alt',
      capsLowercase: 'alt',
      capsUppercase: 'alt',
    },
    en: {
      lowercase: 'alt',
      uppercase: 'alt',
      capsLowercase: 'alt',
      capsUppercase: 'alt',
    },
    special: true,
    double: false,
  },
  {
    key: 'ControlRight',
    ru: {
      lowercase: 'ctrl',
      uppercase: 'ctrl',
      capsLowercase: 'ctrl',
      capsUppercase: 'ctrl',
    },
    en: {
      lowercase: 'ctrl',
      uppercase: 'ctrl',
      capsLowercase: 'ctrl',
      capsUppercase: 'ctrl',
    },
    special: true,
    double: false,
  },
  {
    key: 'ArrowDown',
    ru: {
      lowercase: '↓',
      uppercase: '↓',
      capsLowercase: '↓',
      capsUppercase: '↓',
    },
    en: {
      lowercase: '↓',
      uppercase: '↓;',
      capsLowercase: '↓',
      capsUppercase: '↓',
    },
    double: false,
  },
  {
    key: 'ArrowRight',
    ru: {
      lowercase: '→',
      uppercase: '→',
      capsLowercase: '→',
      capsUppercase: '→',
    },
    en: {
      lowercase: '→',
      uppercase: '→',
      capsLowercase: '→',
      capsUppercase: '→',
    },
    double: false,
  },
];

export default keys;
